"""tabela usuarios

Revision ID: 123ccd6e1824
Revises:
Create Date: 2025-11-02 18:08:16.382019

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "123ccd6e1824"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=200), nullable=False),
        sa.Column("telephone_number", sa.String(length=30), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("adm", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
