"""Remocao do campo 'sent' em certificate

Revision ID: 66e2ceb5f9b7
Revises: 6f9bb3be6b11
Create Date: 2025-11-17 15:59:47.527185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e2ceb5f9b7'
down_revision = '6f9bb3be6b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('sent_by_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_by_email', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
