"""add event_participants many-to-many table

Revision ID: 8800ca51201e
Revises: a5a4568bef8a
Create Date: 2025-11-10 23:09:47.998732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8800ca51201e'
down_revision = 'a5a4568bef8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_participants_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_participants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_participants')),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    # ### end Alembic commands ###
