"""fix: remoção campo 'time'

Revision ID: a3a7c1933d3f
Revises: 8800ca51201e
Create Date: 2025-11-16 21:52:02.908425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a7c1933d3f'
down_revision = '8800ca51201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))

    # ### end Alembic commands ###
