"""tabela eventos

Revision ID: a64d1398f27d
Revises: c9824411e8fb
Create Date: 2025-11-10 21:43:18.686713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64d1398f27d'
down_revision = 'c9824411e8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('WORKSHOP', 'LECTURE', 'CONFERENCE', 'SEMINAR', 'HACKATHON', 'MEETUP', 'TRAINING', 'WEBINAR', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('institution_organizer', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
