from enum import Enum


class EventType(Enum):
    WORKSHOP = "WORKSHOP"
    LECTURE = "LECTURE"
    CONFERENCE = "CONFERENCE"
    SEMINAR = "SEMINAR"
    HACKATHON = "HACKATHON"
    MEETUP = "MEETUP"
    TRAINING = "TRAINING"
    WEBINAR = "WEBINAR"
    OTHER = "OTHER"
